# Generated by Django 2.2.2 on 2019-06-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('recoder', models.CharField(max_length=128, unique=True, verbose_name='记录人')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='设备名称')),
                ('type', models.CharField(max_length=128, unique=True, verbose_name='型号')),
                ('category', models.CharField(max_length=128, unique=True, verbose_name='种类')),
                ('number', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='编号 ')),
                ('part', models.CharField(max_length=128, unique=True, verbose_name='所属部门')),
                ('location', models.CharField(max_length=128, unique=True, verbose_name='存放位置')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '购入信息',
                'verbose_name_plural': '购入信息',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
    ]
