# Generated by Django 2.2.2 on 2019-06-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20190613_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='recoder',
            field=models.CharField(max_length=128, verbose_name='记录人'),
        ),
    ]
