# Generated by Django 2.2.2 on 2019-06-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20190613_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.CharField(max_length=128, verbose_name='种类'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.CharField(max_length=128, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='location',
            field=models.CharField(max_length=128, verbose_name='存放位置'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='name',
            field=models.CharField(max_length=128, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='part',
            field=models.CharField(max_length=128, verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(max_length=128, verbose_name='型号'),
        ),
    ]
