# Generated by Django 2.2.2 on 2019-06-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20190613_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='recoder',
        ),
    ]
